### ISSUE TITLE
URL for saving app state breaks when deployed on shinyapps.io

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/menu#2]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/4367617/209395930-11cfda4c-e251-42c5-ab3c-41e5b7aadf91.png">

something we have to update in the code that creates the bookmark button?  or changing a setting on shinyapps.io?

**Comment by andrew-vancil** [comment]
So right now, we are saving the app state to the server. While this works locally, it isn't supported when the app is hosted on shinyapps.io. It is however supported on Shiny Server Open Source, Shiny Server Pro, and RStudio Connect. 

There is another option to save all the information in the url, but that gives you an ugly copy pop-up that looks like this:
<img width="1754" alt="Screen Shot 2022-12-27 at 11 25 04 AM" src="https://user-images.githubusercontent.com/72818699/209694053-51b7d4c2-cec9-42f1-8465-2f63acaa406b.png">

I guess there's two options: 1) switch to the messy url copy/paste (but I know you hate long, ugly urls :)) or
2) Move the hosting over to one of the other platforms.

For now, I created a branch from this issue where I pushed up the version with the ugly url if you want to try it locally. Let me know what you think!

**Comment by cole-brokamp** [comment]
Shiny Server is the software, so we would still need somewhere to host it.  RStudio Connect will be a possibility in the future, but I see this issue as something that could be useful across the board for all of our apps.

Maybe we could do something with [remote storage](https://shiny.rstudio.com/articles/persistent-data-storage.html).  Having a short URL to share the "default" app state seems really powerful!

**Comment by cole-brokamp** [comment]
Would it be crazy to use a URL shortener in the application?

https://stackoverflow.com/questions/55186474/url-shortener-in-r-shiny-apps
